server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authuser
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true